# Generated by Django 4.2.11 on 2024-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.IntegerField(default=0)),
                ('arabic_name', models.CharField(max_length=150, null=True)),
                ('arabic_description', models.CharField(max_length=200, null=True)),
                ('english_name', models.CharField(max_length=150, null=True)),
                ('english_description', models.CharField(max_length=200, null=True)),
                ('note', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
